# Generated by Django 5.0.3 on 2025-08-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(db_index=True, default='Chamber A', max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(db_index=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('co2', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.DeleteModel(
            name='SensorReading',
        ),
        migrations.AddConstraint(
            model_name='minutereading',
            constraint=models.UniqueConstraint(fields=('chamber', 'date', 'time'), name='uniq_chamber_minute'),
        ),
    ]
