# Generated by Django 5.0.3 on 2025-08-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_minutereading_delete_sensorreading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutereading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
