# Generated by Django 5.0.3 on 2025-08-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_minutereading_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MinuteReading',
        ),
    ]
