# Generated by Django 5.0.3 on 2025-08-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor', '0004_delete_minutereading'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(db_index=True)),
                ('temperature', models.FloatField()),
                ('temperature1', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField()),
                ('humidity1', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.AddConstraint(
            model_name='sensordata',
            constraint=models.CheckConstraint(check=models.Q(('temperature__gte', -50), ('temperature__lte', 150)), name='temp_0_in_range'),
        ),
        migrations.AddConstraint(
            model_name='sensordata',
            constraint=models.CheckConstraint(check=models.Q(('humidity__gte', 0), ('humidity__lte', 100)), name='hum_0_in_range'),
        ),
    ]
