# Generated by Django 5.0.3 on 2025-08-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='chamber',
            field=models.CharField(choices=[('A', 'Chamber 1'), ('B', 'Chamber 2'), ('C', 'Chamber 3')], db_index=True, default='A', max_length=1),
        ),
    ]
