# Generated by Django 5.0.3 on 2025-08-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_sensordata_chamber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='chamber',
        ),
    ]
