# Generated by Django 5.0.3 on 2025-08-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0007_remove_sensordata_chamber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamber2Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(db_index=True)),
                ('temperature', models.FloatField()),
                ('temperature1', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField()),
                ('humidity1', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Chamber 2 Reading',
                'verbose_name_plural': 'Chamber 2 Readings',
                'db_table': 'chamber2_data',
            },
        ),
        migrations.CreateModel(
            name='Chamber3Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(db_index=True)),
                ('temperature', models.FloatField()),
                ('temperature1', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField()),
                ('humidity1', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Chamber 3 Reading',
                'verbose_name_plural': 'Chamber 3 Readings',
                'db_table': 'chamber3_data',
            },
        ),
        migrations.RenameModel(
            old_name='SensorData',
            new_name='Chamber1Data',
        ),
        migrations.AlterModelOptions(
            name='chamber1data',
            options={'verbose_name': 'Chamber 1 Reading', 'verbose_name_plural': 'Chamber 1 Readings'},
        ),
        migrations.RemoveConstraint(
            model_name='chamber1data',
            name='temp_0_in_range',
        ),
        migrations.RemoveConstraint(
            model_name='chamber1data',
            name='hum_0_in_range',
        ),
        migrations.AlterModelTable(
            name='chamber1data',
            table='chamber1_data',
        ),
    ]
