# Generated by Django 5.0.3 on 2025-09-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0009_chamberaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamber1data',
            old_name='humidity1',
            new_name='co2',
        ),
        migrations.RenameField(
            model_name='chamber1data',
            old_name='temperature1',
            new_name='pressure',
        ),
        migrations.RenameField(
            model_name='chamber2data',
            old_name='humidity1',
            new_name='co2',
        ),
        migrations.RenameField(
            model_name='chamber2data',
            old_name='temperature1',
            new_name='pressure',
        ),
        migrations.RenameField(
            model_name='chamber3data',
            old_name='humidity1',
            new_name='co2',
        ),
        migrations.RenameField(
            model_name='chamber3data',
            old_name='temperature1',
            new_name='pressure',
        ),
        migrations.AlterUniqueTogether(
            name='chamberaccess',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chamberaccess',
            name='chamber',
            field=models.CharField(choices=[('ch1', 'Chamber 1'), ('ch2', 'Chamber 2'), ('ch3', 'Chamber 3')], max_length=3),
        ),
    ]
