# Generated by Django 5.0.3 on 2025-09-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0010_rename_humidity1_chamber1data_co2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber1data',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamber1data',
            name='time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamber2data',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamber2data',
            name='time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamber3data',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamber3data',
            name='time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
    ]
