# Generated by Django 5.0.3 on 2025-09-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0011_alter_chamber1data_date_alter_chamber1data_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber1data',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamber1data',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamber2data',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamber2data',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamber3data',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamber3data',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
